### ISSUE TITLE
Task constructor accepts an array

### ISSUE THREAD

**Issue by sagikazarmark** [indigophp/robo-iless#3]
...but the example uses an extra `path` method to pass files.

**Comment by TamasBarta** [comment]
Both works now. I want to remove the parameter from the constructor, I think that is a better way to go than removing the method. I'm not sure it's a problem to support both though. What do you think?

**Comment by sagikazarmark** [comment]
Currently you have to use the constructor param right now, thus the example does not work.

I suggest you checking the minify command which is also related to assets.

**Comment by TamasBarta** [comment]
```
<?php
$this->taskMinify( 'web/assets/theme.css' )
     ->run()
?>
```

I use that, but It's documentation is really cheap, and also it's interface is overly minimalistic (I'm aware of `->to($path)`. It's enough, and that's what inspired me to create the constructor parameter. I like the consistency of the setter version with other setters, but I believe it's not a problem if you have choice over this. It's the constructor parameter that should be made optional.

**Comment by sagikazarmark** [comment]
Honestly, I don't care which way you choose as long as it works and the example is a working sample as well. It is so trivial IMO. Both works for me.

**Comment by TamasBarta** [comment]
Ok, it just wasn't obvious for me what your issue was from the original wording.

**Comment by TamasBarta** [comment]
Wow. Really. What is your issue? I looked at the example, and the code, and the constructor's first parameter is optional. It really should work, if you're not referring to something else.

**Comment by sagikazarmark** [comment]
I pasted the example to a robo file and it triggered an error saying the constructor parameter is required.

**Comment by TamasBarta** [comment]
Take a look at https://github.com/indigophp/robo-iless/blob/master/src/Task/ILess/CompileLessTask.php#L37

I believe you got a wrong version maybe? I'm not sure. Or I'm derping really hard right now not seeing the problem with this constructor.

**Comment by sagikazarmark** [comment]
Actually the problem is with [this](https://github.com/indigophp/robo-iless/blob/master/src/Task/ILess/loadTasks.php#L10) line.

**Comment by TamasBarta** [comment]
Thanks, fixed.
